# Use an official OpenJDK 17 runtime as a parent image
FROM bellsoft/liberica-openjdk-alpine:17

# Set the working directory to /app
WORKDIR /app

# Copy the JAR file into the container at /app
COPY target/Jpademo-0.0.1-SNAPSHOT.jar /app/Jpademo-0.0.1-SNAPSHOT.jar

# Make port 8082, 9091 available to the world outside this container
EXPOSE 8082, 9091

# Run the JAR file when the container starts
CMD ["java", "-jar", "Jpademo-0.0.1-SNAPSHOT.jar"]